import type { Term } from '../../components/Glossary';

export const ALCOHOL_GLOSSARY_TERMS: Term[] = [
  { id: 'mps', abbr: 'MPS', cn: '肌肉蛋白合成', refs: [{ label: 'StatPearls', url: 'https://www.ncbi.nlm.nih.gov/books/NBK573060/' }], abstract: { zh: '肌肉把氨基酸合成为新蛋白的过程。', en: 'The process of incorporating amino acids into new muscle proteins.' }, inArticle: { zh: '用于衡量训练后肌肉合成反应；酒精暴饮后的 MPS 下降是本文的核心人体结局。', en: 'The primary post-exercise muscle outcome discussed in this article.' } },
  { id: 'adh', abbr: 'ADH', cn: '乙醇脱氢酶', refs: [{ label: 'NCBI Bookshelf', url: 'https://www.ncbi.nlm.nih.gov/books/NBK526054/' }], abstract: { zh: '将乙醇氧化为乙醛的酶。', en: 'An enzyme that oxidizes ethanol to acetaldehyde.' }, inArticle: { zh: '乙醇代谢的第一步。', en: 'The first major step in ethanol metabolism.' } },
  { id: 'aldh', abbr: 'ALDH', cn: '乙醛脱氢酶', refs: [{ label: 'NCBI Gene', url: 'https://www.ncbi.nlm.nih.gov/gene/217' }], abstract: { zh: '将乙醛进一步氧化为乙酸盐的酶。', en: 'An enzyme that further oxidizes acetaldehyde to acetate.' }, inArticle: { zh: '与 ADH 一起决定乙醇如何进入乙酸盐代谢路径。', en: 'Together with ADH, it determines how ethanol enters acetate metabolism.' } },
  { id: 'nadh', abbr: 'NADH', cn: '还原型辅酶', refs: [], abstract: { zh: '参与氧化还原反应的辅酶；乙醇代谢会增加 NADH。', en: 'A redox coenzyme whose level rises during ethanol metabolism.' }, inArticle: { zh: 'NADH/NAD⁺ 比值升高会改变脂肪酸氧化和糖异生。', en: 'A higher NADH/NAD⁺ ratio alters fatty-acid oxidation and gluconeogenesis.' } },
  { id: 'dnL', abbr: 'DNL', cn: '脂肪从头合成', refs: [{ label: 'NCBI Bookshelf', url: 'https://www.ncbi.nlm.nih.gov/books/NBK22436/' }], abstract: { zh: '把非脂肪底物转化为脂肪酸的代谢过程。', en: 'The metabolic conversion of non-fat substrates into fatty acids.' }, inArticle: { zh: '用于区分酒精直接转脂肪与酒精抑制脂肪氧化这两个问题。', en: 'Used to distinguish direct conversion of alcohol to fat from suppressed fat oxidation.' } },
  { id: 'sick-quitter', abbr: 'Sick-quitter bias', cn: '因病戒酒者偏倚', refs: [], abstract: { zh: '把因健康变差而戒酒的人归入不饮酒组造成的观察性研究偏倚。', en: 'Bias caused when people who quit drinking because of poor health are grouped with lifelong abstainers.' }, inArticle: { zh: '解释观察性研究中“适量饮酒可能保护肌肉”的结果为何不能直接当作因果证据。', en: 'Explains why apparent protective associations in observational studies are not causal evidence.' } },
  { id: 'translation-initiation', abbr: 'eIF2B / eIF4E', cn: '翻译起始因子', refs: [], abstract: { zh: '参与 mRNA 翻译起始的蛋白复合体和因子。', en: 'Factors and complexes involved in translation initiation.' }, inArticle: { zh: '用于解释酒精如何影响肌肉蛋白合成信号。', en: 'Used to explain how alcohol can affect muscle-protein-synthesis signaling.' } },
];
