import type { Term } from '../../components/Glossary';

export const SUPPLEMENT_GLOSSARY_TERMS: Term[] = [
  { id: 'mps', abbr: 'MPS', cn: '肌肉蛋白合成', refs: [{ label: 'PubMed', url: 'https://pubmed.ncbi.nlm.nih.gov/19056590/' }], abstract: { zh: '肌肉制造新蛋白的过程。', en: 'The process of making new muscle protein.' }, inArticle: { zh: '用于区分短期生理反应和长期肌肥大。', en: 'Used to distinguish acute physiology from long-term hypertrophy.' } },
  { id: 'mpb', abbr: 'MPB', cn: '肌肉蛋白分解', refs: [], abstract: { zh: '肌肉蛋白被分解的过程。', en: 'The process of breaking down muscle protein.' }, inArticle: { zh: '与 MPS 共同决定净蛋白平衡。', en: 'Together with MPS, it determines net protein balance.' } },
  { id: 'mtorc1', abbr: 'mTORC1', cn: '合成代谢信号枢纽', refs: [{ label: 'KEGG', url: 'https://www.genome.jp/pathway/hsa04150' }], abstract: { zh: '整合营养、机械和激素信号的细胞生长通路。', en: 'A growth pathway integrating nutrient, mechanical and hormonal signals.' }, inArticle: { zh: '用于解释训练和蛋白质如何影响合成信号。', en: 'Used to explain how training and protein affect anabolic signaling.' } },
  { id: 'ampk', abbr: 'AMPK', cn: '细胞能量感受器', refs: [{ label: 'KEGG', url: 'https://www.genome.jp/pathway/hsa04152' }], abstract: { zh: '能量不足时被激活的细胞能量传感器。', en: 'A cellular energy sensor activated during low-energy states.' }, inArticle: { zh: '用于解释能量赤字和训练应激。', en: 'Used to explain energy deficit and exercise stress.' } },
  { id: 'ffm', abbr: 'FFM', cn: '去脂体重', refs: [], abstract: { zh: '体重减去脂肪后的部分，包含肌肉、骨骼和水分。', en: 'Body mass excluding fat, including muscle, bone and water.' }, inArticle: { zh: '用于判断体成分变化，而不是直接等同肌肉。', en: 'Used to discuss body composition without equating it directly with muscle.' } },
  { id: 'rct', abbr: 'RCT', cn: '随机对照试验', refs: [{ label: 'Cochrane', url: 'https://www.cochrane.org/evidence' }], abstract: { zh: '通过随机分组比较干预和对照的研究设计。', en: 'A study design randomly comparing an intervention with a control.' }, inArticle: { zh: '用于区分较强的因果证据和观察性线索。', en: 'Used to distinguish stronger causal evidence from observational signals.' } },
  { id: 'trt', abbr: 'TRT', cn: '睾酮替代治疗', refs: [{ label: 'Endocrine Society', url: 'https://www.endocrine.org/clinical-practice-guidelines/testosterone-therapy' }], abstract: { zh: '针对确诊性腺功能减退的医疗治疗。', en: 'Medical treatment for confirmed hypogonadism.' }, inArticle: { zh: '与非医疗超生理 AAS 使用严格分开。', en: 'Kept separate from nonmedical supraphysiologic AAS use.' } },
  { id: 'aas', abbr: 'AAS', cn: '合成代谢雄激素类固醇', refs: [{ label: 'PubMed', url: 'https://pubmed.ncbi.nlm.nih.gov/28533317/' }], abstract: { zh: '具有合成代谢和雄激素作用的一类激素药物。', en: 'Hormonal drugs with anabolic and androgenic effects.' }, inArticle: { zh: '用于讨论超生理非医疗使用及其风险。', en: 'Used for nonmedical supraphysiologic use and its risks.' } },
  { id: 'hpta', abbr: 'HPTA', cn: '下丘脑-垂体-睾丸轴', refs: [], abstract: { zh: '调节男性生殖激素和精子生成的内分泌轴。', en: 'The endocrine axis regulating male reproductive hormones and sperm production.' }, inArticle: { zh: '用于解释外源雄激素对内源睾酮的抑制。', en: 'Used to explain suppression of endogenous testosterone by exogenous androgens.' } },
  { id: 'sarm', abbr: 'SARM', cn: '选择性雄激素受体调节剂', refs: [], abstract: { zh: '设计为选择性作用于雄激素受体的一类化合物。', en: 'Compounds designed for selective androgen-receptor activity.' }, inArticle: { zh: '作为与 AAS 相邻但证据和监管不同的风险类别。', en: 'A related but distinct risk category from AAS.' } },
];
