import type { EvidenceClaim, EvidenceSource } from '../../components/EvidenceIndex';

export const EVIDENCE_SOURCES: EvidenceSource[] = [
  { id: 'creatine-regional', label: 'Candow et al. 2023', detail: 'Systematic review and meta-analysis; 10 studies and 44 imaging outcomes for creatine plus resistance training', level: 'A', url: 'https://pubmed.ncbi.nlm.nih.gov/37432300/' },
  { id: 'creatine-lbm', label: 'Forbes et al. 2022', detail: 'Systematic review and meta-analysis; 35 randomized trials and 1,192 participants', level: 'A', url: 'https://pubmed.ncbi.nlm.nih.gov/35986981/' },
  { id: 'protein-meta', label: 'Morton et al. 2018', detail: 'Systematic review, meta-analysis and meta-regression; 49 trials and 1,863 healthy adults', level: 'A', url: 'https://pubmed.ncbi.nlm.nih.gov/28698222/' },
  { id: 'protein-carb', label: 'Furrer et al. 2026', detail: 'Randomized trial of intra-workout protein-carbohydrate versus isocaloric carbohydrate during resistance training', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/42514376/' },
  { id: 'carbohydrate-energy', label: 'Carbohydrate-energy crossover trial 2026', detail: 'Counterbalanced crossover trial in 20 resistance-trained men; 8-week periods', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/42356347/' },
  { id: 'caffeine', label: 'Grgic et al. 2020', detail: 'Umbrella review of caffeine supplementation and exercise performance', level: 'A', url: 'https://pubmed.ncbi.nlm.nih.gov/30926628/' },
  { id: 'beta-alanine', label: 'Trexler et al. 2015', detail: 'ISSN position stand on beta-alanine, carnosine and exercise performance', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/26175657/' },
  { id: 'citrulline', label: 'Prokopidis et al. 2025', detail: 'Systematic review and dose-response meta-analysis; 21 trials of citrulline/watermelon and body composition', level: 'A', url: 'https://pubmed.ncbi.nlm.nih.gov/41097202/' },
  { id: 'hmb', label: 'Holeček et al. 2020', detail: 'Systematic review and meta-analysis of HMB during resistance training in young subjects', level: 'A', url: 'https://pubmed.ncbi.nlm.nih.gov/32456217/' },
  { id: 'vitamin-d', label: 'Vitamin D3 soccer trial 2026', detail: 'Double-blind randomized trial; professional female soccer players with baseline performance context', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/42588083/' },
  { id: 'ristow', label: 'Ristow et al. 2009', detail: 'Randomized human exercise study of high-dose vitamin C/E and training adaptations', level: 'A', url: 'https://pubmed.ncbi.nlm.nih.gov/19433800/' },
  { id: 'paulsen', label: 'Paulsen et al. 2014', detail: 'Randomized resistance-training study of vitamin C/E and physiological adaptations', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/25075311/' },
  { id: 'trt-guideline', label: 'Endocrine Society 2018', detail: 'Clinical practice guideline for diagnosis, indications, contraindications and monitoring', level: 'E', url: 'https://www.endocrine.org/clinical-practice-guidelines/testosterone-therapy' },
  { id: 'trt-guideline-bhasin', label: 'Bhasin et al. 2018', detail: 'Endocrine Society clinical practice guideline for testosterone therapy in men with hypogonadism', level: 'E', url: 'https://pubmed.ncbi.nlm.nih.gov/29562364/' },
  { id: 'traverse', label: 'Lincoff et al. 2023', detail: 'TRAVERSE randomized noninferiority trial of testosterone replacement and cardiovascular events', level: 'A', url: 'https://pubmed.ncbi.nlm.nih.gov/37326322/' },
  { id: 'trt-benefit', label: 'Snyder et al. 2016', detail: 'Testosterone Trials analysis of sexual function in older men with low testosterone', level: 'A', url: 'https://pubmed.ncbi.nlm.nih.gov/27355400/' },
  { id: 'aas-cardiovascular', label: 'Baggish et al. 2017', detail: 'Cardiovascular toxicity of illicit anabolic-androgenic steroid use', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/28533317/' },
  { id: 'bhasin-dose', label: 'Bhasin et al. 1996', detail: 'Short-term randomized dose-response trial of supraphysiologic testosterone in healthy men', level: 'A', url: 'https://pubmed.ncbi.nlm.nih.gov/8637535/' },
  { id: 'haarlem', label: 'HAARLEM study 2021', detail: 'One-year prospective cohort of 100 men beginning nonmedical androgen use', level: 'C', url: 'https://pubmed.ncbi.nlm.nih.gov/33038020/' },
  { id: 'omega3-review', label: 'Smith et al. 2011', detail: 'Human omega-3 study examining muscle protein anabolic response in older adults', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/21501117/' },
  { id: 'ashwagandha-review', label: 'Walton et al. 2026', detail: 'Recent review of Withania somnifera and cognitive/physical outcomes', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/42199854/' },
  { id: 'metformin-exercise', label: 'Konopka et al. 2019', detail: 'Randomized study of metformin and mitochondrial adaptations to aerobic exercise', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/30548390/' },
  { id: 'tribulus', label: 'Antonio et al. 2000', detail: 'Randomized trial of Tribulus terrestris in resistance-trained men', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/10861339/' },
  { id: 'daa', label: 'Topo et al. 2009', detail: 'Human and animal mechanistic study of D-aspartic acid and LH/testosterone synthesis', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/19860889/' },
  { id: 'daa-training', label: 'Willoughby et al. 2013', detail: 'Randomized resistance-training study of D-aspartic acid supplementation', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/24074738/' },
  { id: 'bicarbonate', label: 'Trexler et al. 2021', detail: 'ISSN position stand on sodium bicarbonate and exercise performance', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/34503527/' },
  { id: 'carnitine', label: 'Nutritional interventions umbrella review 2024', detail: 'Umbrella review of nutritional interventions for exercise-induced muscle damage and recovery', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/37460208/' },
  { id: 'presleep-protein', label: 'Snijders et al. 2019', detail: 'Review of pre-sleep protein ingestion and skeletal-muscle adaptation', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/30895177/' },
  { id: 'peptides-gap', label: 'van Amsterdam et al. 2022', detail: 'Review discussing AAS-adjacent compounds and the limitations of nonmedical evidence', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/36644692/' },
  { id: 'eurycoma', label: 'Ismail et al. 2012', detail: 'Randomized clinical trial of Eurycoma longifolia extract', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/23243445/' },
  { id: 'otc-review', label: 'Clemesha et al. 2020', detail: 'Review of testosterone-boosting supplement composition and claims', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/31385468/' },
  { id: 'fenugreek-pilot', label: 'Wankhede et al. 2016', detail: 'Eight-week randomized pilot of a standardized fenugreek glycoside extract during resistance training', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/30356905/' },
  { id: 'fenugreek-strength', label: 'Poole et al. 2010', detail: 'Eight-week double-blind trial of a commercial botanical supplement in resistance-trained men', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/20979623/' },
  { id: 'myonuclear-memory', label: 'Egner et al. 2013', detail: 'Cellular memory mechanism after anabolic steroid exposure', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/24167222/' },
  { id: 'rhodiola', label: 'Olsson et al. 2009', detail: 'Randomized human study of Rhodiola and stress-related fatigue', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/19016404/' },
  { id: 'rhodiola-acute', label: 'Spasov et al. 2000', detail: 'Placebo-controlled pilot study of Rhodiola and fatigue', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/10839209/' },
  { id: 'nad', label: 'Airhart et al. 2017', detail: 'Human pharmacokinetic study of nicotinamide riboside', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/29211728/' },
  { id: 'nad-tolerability', label: 'Martens et al. 2018', detail: 'Chronic nicotinamide riboside supplementation and tolerability', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/29599478/' },
  { id: 'aas-review', label: 'van Amsterdam et al. 2022', detail: 'Review of anabolic-androgenic steroid pharmacology and multi-system risks', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/36644692/' },
  { id: 'aas-clinical', label: 'Rahnema et al. 2019', detail: 'Clinical review of diagnosis and management of anabolic-androgenic steroid use', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/30753550/' },
  { id: 'aas-dependence', label: 'Kanayama et al. 2010', detail: 'Clinical review of treatment of anabolic-androgenic steroid dependence', level: 'B', url: 'https://pubmed.ncbi.nlm.nih.gov/20188494/' },
];

export const EVIDENCE_CLAIMS: EvidenceClaim[] = [
  { id: 'creatine-hypertrophy', section: '肌酸', text: '肌酸是少数同时具备机制、训练和组织终点证据的补剂', result: '区域性肌肥大 Meta 纳入 10 项研究、44 个影像学结局；另一项 Meta 纳入 35 项 RCT、1,192 名受试者。', basis: '证据支持总体有效性，但个体增益受年龄、性别、训练经验、测量部位和饮食影响。', level: 'A', sourceIds: ['creatine-regional', 'creatine-lbm'] },
  { id: 'protein-total', section: '蛋白质', text: '蛋白质首先用于补足每日总量', result: 'Morton Meta 纳入 49 项 RCT、1,863 名健康成人，评估蛋白补充与抗阻训练的瘦体重和力量结局。', basis: '这支持训练背景下的总体增益，不支持无限提高蛋白质会无限增肌。', level: 'A', sourceIds: ['protein-meta'] },
  { id: 'protein-carb', section: '蛋白质与碳水', text: '训练中蛋白质-碳水的增量价值仍需看具体场景', result: '小样本 RCT 在非空腹状态下比较训练中蛋白质-碳水与等热量碳水。', basis: '该设计有现实相关性，但样本和观察窗口不足以生成普遍处方。', level: 'B', sourceIds: ['protein-carb'] },
  { id: 'carbohydrate-energy', section: '蛋白质与碳水', text: '已有训练者额外增加碳水，不应默认等于更多肌肉', result: '交叉试验在 20 名训练男性中比较蛋白质基础补充与额外碳水-能量补充，每阶段 8 周。', basis: '研究可以检验增量价值，但不能把单个交叉试验外推到所有训练者。', level: 'B', sourceIds: ['carbohydrate-energy'] },
  { id: 'caffeine-performance', section: '咖啡因', text: '咖啡因主要是急性训练表现工具', result: 'Umbrella review 汇总咖啡因与运动表现研究。', basis: '急性表现改善不能自动换算为长期肌肉量增加；睡眠受损可能抵消训练收益。', level: 'A', sourceIds: ['caffeine'] },
  { id: 'beta-alanine', section: 'β-丙氨酸', text: 'β-丙氨酸更适合特定时长的高强度运动', result: 'ISSN position stand 汇总 β-丙氨酸、肌肽和运动表现证据。', basis: '该证据支持运动表现定位，不足以将 β-丙氨酸视为通用长期增肌药。', level: 'B', sourceIds: ['beta-alanine'] },
  { id: 'bicarbonate', section: '碳酸氢钠', text: '碳酸氢钠可能帮助特定高强度表现，但不能直接视为长期增肌补剂', result: 'ISSN position stand 汇总碳酸氢钠与运动表现证据。', basis: '表现收益依赖运动项目和耐受性；胃肠道不适可能抵消收益，长期肌肥大证据不足。', level: 'B', sourceIds: ['bicarbonate'] },
  { id: 'citrulline-body-composition', section: '瓜氨酸', text: '瓜氨酸尚无已证实的直接增肌效果', result: '体成分剂量-反应 Meta 纳入 21 项 RCT，摘要指出 BMI、体重、脂肪量和腰围没有实质性总体影响。', basis: '泵感、血流或训练表现终点与长期体成分终点不是同一问题。', level: 'A', sourceIds: ['citrulline'] },
  { id: 'hmb-young', section: 'HMB', text: 'HMB 在年轻训练者中没有稳定的增肌增量证据', result: '系统综述与 Meta 分析针对年轻受试者的抗阻训练，题名结论为未改善体成分或力量。', basis: '不能把年轻训练者结果外推至老年、卧床或疾病相关肌肉流失人群。', level: 'A', sourceIds: ['hmb'] },
  { id: 'vitamin-d', section: '维生素 D', text: '维生素 D 更像缺乏纠正措施，而不是默认增肌药', result: '专业女足 RCT 使用 D3 4000 IU/日 8 周；在基线充足情境下未见速度或功率进一步改善。', basis: '该结果不等于缺乏者无效，也不支持充足状态下继续加量。', level: 'B', sourceIds: ['vitamin-d'] },
  { id: 'antioxidants', section: '抗氧化剂', text: '高剂量维生素 C/E 不应作为增肌工具', result: '两项人体训练研究观察到高剂量抗氧化剂可能改变或削弱部分训练适应信号。', basis: '不等于水果和蔬菜有害；问题是把高剂量单一抗氧化剂当作固定恢复方案。', level: 'A', sourceIds: ['ristow', 'paulsen'] },
  { id: 'trt-indication', section: 'TRT', text: 'TRT 的适应证是确诊性腺功能减退，不是普通增肌', result: 'Endocrine Society 与 Bhasin 等人指南要求症状、可靠且重复的低睾酮检测和病因评估，并规定禁忌证与监测。', basis: '生理范围内的替代治疗不能外推为健康人的超生理增肌方案。', level: 'E', sourceIds: ['trt-guideline', 'trt-guideline-bhasin'] },
  { id: 'traverse-safety', section: 'TRT', text: 'TRAVERSE 的安全结论只适用于被研究的 TRT 人群和治疗框架', result: 'TRAVERSE 研究有症状、确认低睾酮且心血管风险较高的男性，目标是维持生理范围。', basis: '不能把该试验外推到 AAS、多药联用、黑市产品或超生理暴露。', level: 'A', sourceIds: ['traverse'] },
  { id: 'omega3-boundary', section: '鱼油', text: '鱼油不能从恢复信号直接推导为长期增肌', result: '人体研究关注 omega-3 与肌肉蛋白合成反应，研究人群和终点有明确限制。', basis: '鱼油的抗炎或 MPS 结果不能自动替代长期 FFM、肌肉厚度和力量终点。', level: 'B', sourceIds: ['omega3-review'] },
  { id: 'metformin-boundary', section: '二甲双胍', text: '改善代谢疾病不等于适合健康增肌优化', result: '随机研究关注二甲双胍与运动适应的相互作用。', basis: '药物适应证、疾病获益和健康训练者的肌肥大目标必须分开。', level: 'B', sourceIds: ['metformin-exercise'] },
  { id: 'carnitine-boundary', section: '肉碱', text: '肉碱的恢复信号不能直接证明长期肌肥大', result: '伞形综述汇总营养干预与运动诱发肌损伤、酸痛和恢复的研究。', basis: '恢复终点和长期肌肉量、肌肉厚度或力量终点不同；人群和产品差异限制外推。', level: 'B', sourceIds: ['carnitine'] },
  { id: 'ashwagandha-boundary', section: '南非醉茄', text: '南非醉茄的力量和恢复结论受样本、周期和提取物标准化限制', result: '现有研究覆盖认知和身体结局，但不是统一制剂、统一训练人群的长期肌肥大试验。', basis: '不能把某一提取物或小样本结果外推成稳定增肌效果。', level: 'B', sourceIds: ['ashwagandha-review'] },
  { id: 'aas-mechanism-risk', section: 'AAS', text: 'AAS 的药理机制和多系统风险不能用补剂安全逻辑解释', result: '综述覆盖 AAS 受体作用、非医疗高剂量暴露和心血管、肝肾、生殖及精神风险。', basis: '机制综述能解释风险方向，但不能给出个人安全阈值或安全周期。', level: 'B', sourceIds: ['aas-review'] },
  { id: 'bhasin-efficacy', section: 'AAS', text: '超生理睾酮的短期增肌效果有研究，但短期有效不等于长期安全', result: 'Bhasin 1996 是短期随机剂量-反应试验，观察健康男性的瘦体重和力量。', basis: '该研究回答短期有效性，未建立多年暴露的安全剂量或安全周期。', level: 'A', sourceIds: ['bhasin-dose'] },
  { id: 'haarlem-risk', section: 'AAS', text: 'AAS 真实世界研究记录风险，不是安全周期验证', result: 'HAARLEM 对 100 名准备开始非医疗雄激素使用的男性进行一年期前瞻性随访。', basis: '队列可描述收益和伤害，但不能证明某个周期、叠加或监测方案安全。', level: 'C', sourceIds: ['haarlem'] },
  { id: 'aas-management', section: 'AAS', text: 'AAS 使用者的临床重点是识别风险、处理并发症和支持停用', result: '临床综述覆盖 AAS 的药理、风险、停用后内分泌问题、依赖和就医管理。', basis: '该文献支持临床评估与减害边界，不支持自行制定用药方案。', level: 'B', sourceIds: ['aas-review', 'aas-clinical', 'aas-dependence'] },
  { id: 'tribulus', section: 'OTC 促睾', text: '刺蒺藜没有稳定的人体促睾或增肌证据', result: 'Antonio 等人的人体随机试验评估了刺蒺藜与体成分和运动表现。', basis: '动物机制或社区宣传不足以证明健康训练者的长期增肌效果。', level: 'B', sourceIds: ['tribulus'] },
  { id: 'daa', section: 'OTC 促睾', text: 'DAA 的急性激素信号不能替代长期肌肉终点', result: 'Topo 研究了 DAA 与 LH/睾酮释放和合成；Willoughby 研究了 DAA 与抗阻训练。', basis: '急性激素变化和长期体成分、力量结果必须分开解读。', level: 'B', sourceIds: ['daa', 'daa-training'] },
  { id: 'eurycoma', section: 'OTC 促睾', text: '东革阿里的临床结果不能直接外推为年轻训练者增肌', result: 'Ismail 等人的人体临床试验提供了 Eurycoma 的特定人群证据。', basis: '性健康或压力结果不等于年轻训练者的长期肌肥大结果。', level: 'B', sourceIds: ['eurycoma'] },
  { id: 'otc-boundary', section: 'OTC 促睾', text: '“提高睾酮”宣传需要同时核对激素类型、持续时间和长期肌肉终点', result: '促睾补剂综述指出产品成分和宣传主张常缺乏学术支持。', basis: '总睾酮、游离睾酮、短期变化和肌肉组织结果不能混为一谈。', level: 'B', sourceIds: ['otc-review'] },
  { id: 'trt-benefit', section: 'TRT', text: 'TRT 的获益取决于低睾酮、症状和具体结局', result: 'Snyder 等人报告了老年低睾酮男性的性功能研究结果。', basis: '性功能、骨密度、身体功能和肌力不能被一个总体“增肌效果”概括。', level: 'A', sourceIds: ['trt-benefit'] },
  { id: 'aas-cardiovascular', section: 'AAS', text: 'AAS 心血管风险不能由主观感觉排除', result: 'Baggish 等人综述了非法 AAS 使用与心脏结构、功能和冠脉风险的关系。', basis: '影像和观察研究不能给出个人概率，但足以否定“看起来没事就安全”。', level: 'B', sourceIds: ['aas-cardiovascular'] },
  { id: 'myonuclear-memory', section: 'AAS', text: '肌核记忆是研究中的机制现象，不是所有人的永久增肌保证', result: 'Egner 等人研究了 AAS 暴露后的细胞记忆与过载肥大。', basis: '保留时间、个体差异和长期表现仍不能外推为确定结论。', level: 'B', sourceIds: ['myonuclear-memory'] },
  { id: 'rhodiola-boundary', section: '红景天', text: '红景天证据主要集中在疲劳、压力和耐力', result: 'Olsson 与 Spasov 的早期人体研究观察了 Rhodiola 与疲劳/压力相关结局。', basis: '这些研究不能直接证明长期肌肉量增加。', level: 'B', sourceIds: ['rhodiola', 'rhodiola-acute'] },
  { id: 'nad-boundary', section: 'NMN/NR', text: 'NAD⁺ 代谢改善不能直接等同健身增肌', result: 'Airhart 与 Martens 的人体研究提供了 NR 的药代动力学和耐受性资料。', basis: '代谢物、耐受性和长期肌肉组织终点是不同问题。', level: 'B', sourceIds: ['nad', 'nad-tolerability'] },
  { id: 'peptides-gap', section: '肽类与 GHRP', text: 'BPC-157、TB-500 和 GHRP 目前只能视为研究线索，不能作为增肌或修复方案', result: '综述指出非医疗雄激素相关产品和未批准化合物的证据常来自动物、病例或质量不一的产品资料。', basis: '缺少足够可靠的人体长期 RCT，不能建立疗效、剂量或安全结论。', level: 'B', sourceIds: ['peptides-gap'] },
  { id: 'presleep-protein-boundary', section: '睡前蛋白', text: '睡前蛋白可提高夜间 MPS，并可能支持训练适应，但独立于总量的增益仍需谨慎解释', result: '综述汇总睡前蛋白对夜间肌肉蛋白合成和抗阻训练适应的研究。', basis: '这支持其作为营养策略的条件性价值；总蛋白、总能量和训练质量仍决定长期结果。', level: 'B', sourceIds: ['presleep-protein'] },
  { id: 'fenugreek', section: '葫芦巴', text: '葫芦巴有小样本、特定制剂下的有限正向信号，但不能证明普遍增肌', result: '两个八周人体试验分别研究了标准化糖苷提取物和商业葫芦巴复合产品；摘要报告了部分体脂和力量结果。', basis: '制剂、样本和观察期有限；不能外推到所有产品，也不能据此判定稳定促睾。', level: 'B', sourceIds: ['fenugreek-pilot', 'fenugreek-strength'] },
  { id: 'zma-boundary', section: 'ZMA', text: 'ZMA 当前无法证明能提高营养充足训练者的增肌效率', result: '目前没有足够完成核验的 ZMA 研究可以支持确定疗效。', basis: '锌镁缺乏的纠正和营养充足者的额外收益是两个问题。', level: 'B', sourceIds: ['otc-review'] },
];
